import type { IconType } from "react-icons";
import {
  FiHome,
  FiSearch,
  FiUser,
  FiSettings,
  FiBell,
  FiMail,
  FiHeart,
  FiStar,
  FiCheck,
  FiX,
  FiPlus,
  FiTrash2,
  FiEdit2,
  FiArrowRight,
  FiArrowLeft,
  FiChevronDown,
  FiChevronUp,
  FiDownload,
  FiUpload,
  FiCalendar,
  FiClock,
  FiInfo,
  FiAlertCircle,
  FiLock,
  FiLogOut,
} from "react-icons/fi";

/** String name -> react-icons component. Add more entries as needed. */
export const ICONS = {
  home: FiHome,
  search: FiSearch,
  user: FiUser,
  settings: FiSettings,
  bell: FiBell,
  mail: FiMail,
  heart: FiHeart,
  star: FiStar,
  check: FiCheck,
  close: FiX,
  plus: FiPlus,
  trash: FiTrash2,
  edit: FiEdit2,
  "arrow-right": FiArrowRight,
  "arrow-left": FiArrowLeft,
  "chevron-down": FiChevronDown,
  "chevron-up": FiChevronUp,
  download: FiDownload,
  upload: FiUpload,
  calendar: FiCalendar,
  clock: FiClock,
  info: FiInfo,
  alert: FiAlertCircle,
  lock: FiLock,
  logout: FiLogOut,
} satisfies Record<string, IconType>;

export type IconName = keyof typeof ICONS;
